module.exports.categories_bg_image =[
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
    '../assests/cricket.png',
]