module.exports.data = {
    "cricket":
        [
            'Virat Kohli',
            'Rohit Sharma',
            'KL Rahul',
            'Shikhar Dhawan',
            'AB de Villiers',
            'Steve Smith',
            'Kane Williamson',
            'Joe Root',
            'David Warner',
            'Babar Azam',
            'Ross Taylor',
            'Quinton de Kock',
            'Faf du Plessis',
            'Aaron Finch',
            'Jason Roy',
            'Eoin Morgan',
            'Jonny Bairstow',
            'Ben Stokes',
            'Jos Buttler',
            'Chris Gayle',
            'Andre Russell',
            'Shakib Al Hasan',
            'Tamim Iqbal',
            'Mushfiqur Rahim',
            'Mohammad Shahzad',
            'Mohammad Nabi',
            'Rashid Khan',
            'Mitchell Starc',
            'Pat Cummins',
            'Josh Hazlewood',
            'Kagiso Rabada',
            'Quinton de Kock',
            'David Miller',
            'Imran Tahir',
            'Fakhar Zaman',
            'Babar Azam',
            'Shoaib Malik',
            'Shaheen Afridi',
            'Mohammad Hafeez',
            'Shan Masood',
            'Brendon McCullum',
            'Martin Guptill',
            'James Neesham',
            'Kane Williamson',
            'Tom Latham',
            'Trent Boult',
            'Colin Munro',
            'Lockie Ferguson',
            'Neil Wagner',
            'Tom Blundell',
            'Colin de Grandhomme',
            'Jeet Raval',
            'Ross Taylor',
            'Mitchell Santner',
            'Tim Southee',
            'Henry Nicholls',
            'Tom Bruce',
            'Daryl Mitchell',
            'Ajaz Patel',
            'Kyle Jamieson',
            'Jacob Duffy',
            'Conway',
            'Ish Sodhi',
            'Sanjay Manjrekar',
            'Sourav Ganguly',
            'Sachin Tendulkar',
            'Ravi Shastri',
            'Anil Kumble',
            'Sunil Gavaskar',
            'Kapil Dev',
            'Virender Sehwag',
            'Rahul Dravid',
            'Yuvraj Singh',
            'MS Dhoni',
            'Gautam Gambhir',
            'Harbhajan Singh',
            'Zaheer Khan',
            'Mohammad Kaif',
            'Irfan Pathan',
            'Yusuf Pathan',
            'Ravindra Jadeja',
            'Suresh Raina',
            'Ajinkya Rahane',
            'Hardik Pandya',
            'Jasprit Bumrah',
            'Rishabh Pant',
            'Shreyas Iyer',
            'Prithvi Shaw',
            'Mayank Agarwal',
            'Kuldeep Yadav',
            'Navdeep Saini',
            'Shubman Gill',
            'Washington Sundar',
            'Deepak Chahar',
            'Hanuma Vihari',
            'Mohammed Siraj',
            'Axar Patel',
            'Varun Chakravarthy',
            'Ishan Kishan',
            'Shivam Dube',
            'Devdutt Padikkal',
            'Rahul Chahar'
        ],
    "movies": [
        "Dilwale Dulhania Le Jayenge",
        "Sholay",
        "3 Idiots",
        "Lagaan",
        "PK",
        "Taare Zameen Par",
        "Andhadhun",
        "Dangal",
        "Gully Boy",
        "Queen",
        "Golmaal",
        "Kabhi Khushi Kabhie Gham",
        "Chak De! India",
        "Swades",
        "Munna Bhai MBBS",
        "Koi Mil Gaya",
        "Krrish",
        "Barfi!",
        "Drishyam",
        "Bhaag Milkha Bhaag",
        "Padmaavat",
        "Om Shanti Om",
        "My Name is Khan",
        "Kal Ho Naa Ho",
        "Kabir Singh",
        "Rang De Basanti",
        "Dil Chahta Hai",
        "Zindagi Na Milegi Dobara",
        "Lage Raho Munna Bhai",
        "Jab We Met",
        "Devdas",
        "Gadar: Ek Prem Katha",
        "Baahubali: The Beginning",
        "Baahubali 2: The Conclusion",
        "Dhoom",
        "Dhoom 2",
        "Robot",
        "Bajrangi Bhaijaan",
        "Sultan",
        "Baazigar",
        "Kuch Kuch Hota Hai",
        "DDLJ",
        "Kesari",
        "Dabangg",
        "Chennai Express",
        "Raees",
        "Dear Zindagi",
        "Don",
        "Don 2",
        "PK",
        "Ghajini",
        "Koi... Mil Gaya",
        "Fanaa",
        "Guru",
        "Talaash",
        "Race",
        "Race 2",
        "Race 3",
        "Dil Se..",
        "Kabhi Alvida Naa Kehna",
        "Dostana",
        "Kalank",
        "Dil Dhadakne Do",
        "Golmaal Again",
        "Dhamaal",
        "Welcome",
        "Hera Pheri",
        "Andaz Apna Apna",
        "Lage Raho Munna Bhai",
        "Munna Bhai M.B.B.S.",
        "Chupke Chupke",
        "Anand",
        "Namak Halaal",
        "Silsila",
        "Kala Patthar",
        "Sholay",
        "Deewar",
        "Amar Akbar Anthony",
        "Don",
        "Zanjeer",
        "Coolie",
        "Laawaris",
        "Naseeb",
        "Kaalia",
        "Sarkar",
        "Piku",
        "3 Idiots",
        "Bajirao Mastani",
        "Rockstar",
        "Barfi!",
        "Dil Dhadakne Do",
        "Queen",
        "Tanu Weds Manu",
        "Gangs of Wasseypur",
        "Haider",
        "Piku",
        "Pink"
    ],
    "sports": [
        'Football',
        'Basketball',
        'Tennis',
        'Baseball',
        'Golf',
        'Swimming',
        'Athletics',
        'Rugby',
        'Hockey',
        'Boxing',
        'Cycling',
        'Soccer',
        'Badminton',
        'Volleyball',
        'Table Tennis',
        'Skiing',
        'Snowboarding',
        'Surfing',
        'Skateboarding',
        'Gymnastics',
        'Wrestling',
        'Karate',
        'Taekwondo',
        'Judo',
        'Fencing',
        'Archery',
        'Shooting',
        'Canoeing',
        'Kayaking',
        'Rowing',
        'Sailing',
        'Weightlifting',
        'Diving',
        'Triathlon',
        'Handball',
        'Polo',
        'Cricket',
        'Squash',
        'Polo',
        'Water Polo',
        'Lacrosse',
        'Ultimate Frisbee',
        'American Football',
        'Racquetball',
        'Bowling',
        'Billiards',
        'Snooker',
        'Darts',
        'Equestrianism',
        'Polo',
        'Pentathlon',
        'Bobsleigh',
        'Skeleton',
        'Luge',
        'Bobcat',
        'Curling',
        'Biathlon',
        'Bullfighting',
        'Rodeo',
        'Bull Riding',
        'Wingsuit Flying',
        'Base Jumping',
        'Bungee Jumping',
        'Skydiving',
        'Paragliding',
        'Hang Gliding',
        'Free Climbing',
        'Parkour',
        'Kiteboarding',
        'Windsurfing',
        'Freestyle Skiing',
        'Freestyle Snowboarding',
        'Ice Climbing',
        'Rock Climbing',
        'Mountaineering',
        'Highlining',
        'Slacklining',
        'Ballet',
        'Breakdancing',
        'Capoeira',
        'Street Workout',
        'Powerlifting',
        'CrossFit',
        'Bodybuilding',
        'Aerobics',
        'Zumba',
        'Pilates',
        'Yoga',
        'Martial Arts'
    ],
    "animals": [
        "Lion",
        "Tiger",
        "Elephant",
        "Giraffe",
        "Zebra",
        "Monkey",
        "Hippo",
        "Rhino",
        "Kangaroo",
        "Panda",
        "Koala",
        "Penguin",
        "Polar Bear",
        "Grizzly Bear",
        "Puma",
        "Jaguar",
        "Leopard",
        "Cheetah",
        "Wolf",
        "Fox",
        "Hyena",
        "Coyote",
        "Dolphin",
        "Whale",
        "Shark",
        "Octopus",
        "Squid",
        "Starfish",
        "Seahorse",
        "Crocodile",
        "Alligator",
        "Python",
        "Anaconda",
        "Boa Constrictor",
        "Rattlesnake",
        "Cobra",
        "Mongoose",
        "Meerkat",
        "Ostrich",
        "Emu",
        "Flamingo",
        "Pelican",
        "Eagle",
        "Hawk",
        "Falcon",
        "Owl",
        "Sparrow",
        "Robin",
        "Blue Jay",
        "Cardinal",
        "Hummingbird",
        "Woodpecker",
        "Parrot",
        "Macaw",
        "Cockatoo",
        "Canary",
        "Finch",
        "Goldfish",
        "Tropical Fish",
        "Angelfish",
        "Betta Fish",
        "Guppy",
        "Catfish",
        "Salmon",
        "Trout",
        "Bass",
        "Pike",
        "Mackerel",
        "Sardine",
        "Cod",
        "Haddock",
        "Tuna",
        "Duck",
        "Goose",
        "Swan",
        "Pigeon",
        "Crow",
        "Raven",
        "Magpie",
        "Jay",
        "Albatross",
        "Seagull",
        "Pelican",
        "Stork",
        "Crane",
        "Heron",
        "Egret",
        "Ibis",
        "Vulture",
        "Condor",
        "Buzzard",
        "Osprey",
        "Hawk",
        "Falcon",
        "Eagle"
    ],
    "actors": [
        'Shah Rukh Khan',
        'Amitabh Bachchan',
        'Salman Khan',
        'Aamir Khan',
        'Akshay Kumar',
        'Ranbir Kapoor',
        'Hrithik Roshan',
        'Varun Dhawan',
        'Ajay Devgn',
        'Saif Ali Khan',
        'Kareena Kapoor Khan',
        'Deepika Padukone',
        'Priyanka Chopra',
        'Alia Bhatt',
        'Katrina Kaif',
        'Anushka Sharma',
        'Sonam Kapoor',
        'Kangana Ranaut',
        'Shraddha Kapoor',
        'Vidya Balan',
        'Taapsee Pannu',
        'Jacqueline Fernandez',
        'Madhuri Dixit',
        'Kajol',
        'Rani Mukerji',
        'Juhi Chawla',
        'Sridevi',
        'Preity Zinta',
        'Karisma Kapoor',
        'Dia Mirza',
        'Parineeti Chopra',
        'Tabu',
        'Nushrat Bharucha',
        'Bhumi Pednekar',
        'Yami Gautam',
        'Kriti Sanon',
        'Radhika Apte',
        'Disha Patani',
        'Tara Sutaria',
        'Ananya Panday',
        'Janhvi Kapoor',
        'Ishaan Khatter',
        'Sara Ali Khan',
        'Siddhant Chaturvedi',
        'Rajkummar Rao',
        'Vicky Kaushal',
        'Ayushmann Khurrana',
        'Tiger Shroff',
        'Kartik Aaryan',
        'Ranveer Singh',
        'Sushant Singh Rajput',
        'Farhan Akhtar',
        'Arjun Kapoor',
        'Sidharth Malhotra',
        'John Abraham',
        'Randeep Hooda',
        'Diljit Dosanjh',
        'Riteish Deshmukh',
        'Emraan Hashmi',
        'Sanjay Dutt',
        'Jackie Shroff',
        'Anil Kapoor',
        'Bobby Deol',
        'Suniel Shetty',
        'Abhishek Bachchan',
        'Neil Nitin Mukesh',
        'Aditya Roy Kapur',
        'Sunny Deol',
        'Sanjay Kapoor',
        'Chunky Pandey',
        'Nawazuddin Siddiqui',
        'Jimmy Sheirgill',
        'Manoj Bajpayee',
        'Nana Patekar',
        'Paresh Rawal',
        'Pankaj Tripathi',
        'Manoj Kumar',
        'Om Puri',
        'Amrish Puri',
        'Gulshan Grover',
        'Rajpal Yadav',
        'Johnny Lever',
        'Kader Khan',
        'Javed Jaffrey',
        'Alok Nath',
        'Mithun Chakraborty',
        'Anupam Kher',
        'Naseeruddin Shah',
        'Kay Kay Menon',
        'Rajat Kapoor',
        'Ashutosh Rana',
        'Saurabh Shukla',
        'Vijay Raaz',
        'Rajpal Yadav',
        'Sanjay Mishra',
        'Boman Irani',
        'Girish Karnad',
        'Annu Kapoor',
        'Raghuvir Yadav',
        'Rajesh Sharma',
        'Vinay Pathak',
        'Satish Kaushik',
        'Rajendra Gupta',
        'Asrani'
    ],
    "football": [
        'Lionel Messi',
        'Cristiano Ronaldo',
        'Neymar',
        'Kylian Mbappé',
        'Mohamed Salah',
        'Kevin De Bruyne',
        'Robert Lewandowski',
        'Sadio Mané',
        'Harry Kane',
        'Sergio Ramos',
        'Luka Modrić',
        'Sergio Agüero',
        'Eden Hazard',
        'Paul Pogba',
        'Raheem Sterling',
        'Antoine Griezmann',
        'Gareth Bale',
        'Manuel Neuer',
        'Thiago Alcântara',
        'Virgil van Dijk',
        'Sergio Busquets',
        'Karim Benzema',
        'Alisson Becker',
        'Toni Kroos',
        'Joshua Kimmich',
        'Ederson',
        'Jan Oblak',
        'Marcelo',
        'Mohamed Elneny',
        'Heung-min Son',
        'David de Gea',
        'Jordi Alba',
        'Casemiro',
        'Aymeric Laporte',
        'Bruno Fernandes',
        'Romelu Lukaku',
        "N'Golo Kanté",
        'Trent Alexander-Arnold',
        'Marcus Rashford',
        'Thibaut Courtois',
        'Andrew Robertson',
        'Christian Pulisic',
        'Fabinho',
        'Vinícius Júnior',
        'Thomas Müller',
        'Raphaël Varane',
        'Phil Foden',
        'Frenkie de Jong',
        'Hakim Ziyech',
        'Paulo Dybala',
        'Kai Havertz',
        'Gianluigi Donnarumma',
        'James Rodríguez',
        'Ángel Di María',
        'Leroy Sané',
        'Jadon Sancho',
        'Wojciech Szczęsny',
        'Memphis Depay',
        'Luis Suárez',
        'Kasper Schmeichel',
        'Dries Mertens',
        'Marco Verratti',
        'Bernardo Silva',
        'Alex Sandro',
        'Riyad Mahrez',
        'Jérôme Boateng',
        'Álvaro Morata',
        'Wojciech Szczęsny',
        'Ciro Immobile',
        'Mauro Icardi',
        'Koke',
        'Giovani Lo Celso',
        'Jamie Vardy',
        'Miralem Pjanić',
        'Matthijs de Ligt',
        'Lucas Moura',
        'Wilfred Ndidi',
        'Nicolò Barella',
        'Roberto Firmino',
        'Jack Grealish',
        'David Alaba',
        'Alex Telles',
        'Sergej Milinković-Savić',
        'Rodri',
        'Kalidou Koulibaly',
        'Gareth Southgate',
        'Declan Rice',
        'Rúben Neves',
        'Luka Jović',
        'Ousmane Dembélé',
        'Achraf Hakimi',
        'João Félix',
        'Saul Niguez',
        'Zlatan Ibrahimović',
        'Isco',
        'Edinson Cavani'
    ],
    "food": [
        'Butter Chicken',
        'Palak Paneer',
        'Chicken Tikka Masala',
        'Tandoori Chicken',
        'Masala Dosa',
        'Chole Bhature',
        'Biryani',
        'Rogan Josh',
        'Samosa',
        'Paneer Butter Masala',
        'Aloo Gobi',
        'Vada Pav',
        'Idli Sambhar',
        'Dal Makhani',
        'Pani Puri',
        'Gulab Jamun',
        'Rasgulla',
        'Jalebi',
        'Pav Bhaji',
        'Kadhi Pakora',
        'Dhokla',
        'Mutton Curry',
        'Fish Curry',
        'Chicken Curry',
        'Aloo Paratha',
        'Pakora',
        'Kachori',
        'Keema',
        'Malai Kofta',
        'Raita',
        'Kofta',
        'Shahi Paneer',
        'Bhindi Masala',
        'Rice',
        'Naan',
        'Paratha',
        'Pulao',
        'Roti',
        'Tandoori Roti',
        'Biryani',
        'Lassi',
        'Chana Masala',
        'Aloo Tikki',
        'Bhindi Fry',
        'Kadai Paneer',
        'Dahi Vada',
        'Ras Malai',
        'Kheer',
        'Matar Paneer',
        'Malai Chicken',
        'Chicken Korma',
        'Malabar Fish Curry',
        'Butter Naan',
        'Chapati',
        'Chana Saag',
        'Shahi Tukda',
        'Hyderabadi Biryani',
        'Chilli Chicken',
        'Chilli Paneer',
        'Dum Aloo',
        'Fish Fry',
        'Tandoori Fish',
        'Goan Fish Curry',
        'Shrimp Biryani',
        'Paneer Tikka',
        'Tandoori Paneer Tikka',
        'Tandoori Shrimp',
        'Rava Dosa',
        'Kesari Bath',
        'Prawn Fry',
        'Mango Lassi',
        'Gobi Manchurian',
        'Paneer Manchurian',
        'Chicken Manchurian',
        'Butter Garlic Naan',
        'Tandoori Garlic Naan',
        'Chettinad Chicken',
        'Dosa',
        'Uttapam',
        'Mango Kulfi',
        'Chicken 65',
        'Egg Curry',
        'Veg Fried Rice',
        'Egg Fried Rice',
        'Chicken Fried Rice',
        'Gajar Ka Halwa',
        'Rajma',
        'Kadhi Chawal',
        'Pav Bhaji',
        'Chole Kulche',
        'Vegetable Korma',
        'Vegetable Jalfrezi',
        'Vegetable Pakora',
        'Vegetable Biryani',
        'Vegetable Pulao',
        'Aloo Matar',
        'Aloo Methi',
        'Aloo Palak',
        'Aloo Baingan',
        'Baingan Bharta',
        'Bhindi Do Pyaza',
        'Bhindi Fry',
        'Kadai Bhindi',
        'Cauliflower Manchurian',
        'Gobi Masala',
        'Gobi Manchurian',
        'Mushroom Masala',
        'Mushroom Matar',
        'Mushroom Do Pyaza',
        'Paneer Bhurji',
        'Paneer Capsicum',
        'Paneer Do Pyaza',
        'Paneer Jalfrezi',
        'Paneer Kadai',
        'Paneer Makhani',
        'Paneer Palak',
        'Paneer Tikka Masala',
        'Palak Corn',
        'Palak Mushroom',
        'Palak Paneer',
        'Dal Tadka',
        'Dal Fry',
        'Dal Palak',
        'Chana Masala',
        'Chana Saag',
        'Rajma Masala',
        'Rajma Chawal',
        'Kadhi Pakora',
        'Khichdi',
        'Pav Bhaji',
        'Chole Bhature',
        'Masoor Dal',
        'Aloo Paratha',
        'Paneer Paratha',
        'Gobi Paratha',
        'Methi Paratha',
        'Palak Paratha',
        'Pudina Paratha',
        'Thepla',
        'Dhokla',
        'Khaman',
        'Khandvi',
        'Muthiya',
        'Sukhi Bhaji',
        'Undhiyu',
        'Sambhar',
        'Vada',
        'Appam',
        'Idli',
        'Uttapam',
        'Upma',
        'Pongal',
        'Kanji Vada',
        'Khatta Dhokla',
        'Patra',
        'Poha',
        'Rava Dosa',
        'Neer Dosa',
        'Pesarattu',
        'Ragi Dosa',
        'Set Dosa',
        'Veg Momos',
        'Veg Hakka Noodles',
        'Veg Spring Rolls',
        'Veg Fried Rice',
        'Veg Pulao',
        'Kofta Curry',
        'Vegetable Cutlet',
        'Vegetable Sandwich',
        'Vegetable Soup',
        'Mix Vegetable Curry',
        'Vegetable Stew',
        'Vegetable Upma'        
    ],
    "cartoons": [
        'Tom and Jerry',
        'Shinchan',
        'Chhota Bheem',
        'Doraemon',
        'Popeye the Sailor',
        'Motu Patlu',
        'SpongeBob SquarePants',
        'The Powerpuff Girls',
        'Ben 10',
        'DuckTales',
        'Pokémon',
        'Scooby-Doo',
        'Phineas and Ferb',
        'Johnny Bravo',
        'The Flintstones',
        'Teen Titans Go!',
        'Avatar: The Last Airbender',
        'Bob the Builder',
        'Gravity Falls',
        'Adventure Time',
        'The Simpsons',
        'The Smurfs',
        'Aladdin',
        'Sonic the Hedgehog',
        'Inspector Gadget',
        'Hey Arnold!',
        'Dexter\'s Laboratory',
        'The Jetsons',
        'Transformers',
        'The Fairly OddParents',
        'Batman: The Animated Series',
        'Sesame Street',
        'The Magic School Bus',
        'The Looney Tunes Show',
        'My Little Pony: Friendship Is Magic',
        'Dragon Ball Z',
        'Naruto',
        'Yu-Gi-Oh!',
        'Beyblade',
        'Digimon',
        'Boboiboy',
        'Oggy and the Cockroaches',
        'Mickey Mouse Clubhouse',
        'The Lion King\'s Timon & Pumbaa',
        'Winnie the Pooh',
        'The Jungle Book',
        'Tarzan',
        'Kim Possible',
        'Rugrats',
        'Foster\'s Home for Imaginary Friends',
        'Garfield and Friends',
        'The Pink Panther Show',
        'Pingu',
        'Arthur',
        'Pocoyo',
        'Little Krishna',
        'Winx Club',
        'Puppy Dog Pals',
        'Sailor Moon',
        'Shrek',
        'Sylvanian Families',
        'Thomas & Friends',
        'The Adventures of Tintin',
        'The Amazing World of Gumball',
        'The Flintstone Kids',
        'The Lion Guard',
        'The Penguins of Madagascar',
        'The Wild Thornberrys',
        'Tintin',
        'Trollhunters',
        'W.I.T.C.H.',
        'Wallykazam!',
        'Wild Kratts',
        'Woody Woodpecker',
        'Zig & Sharko',
        'Curious George',
        'Captain Planet and the Planeteers',
        'Care Bears',
        'Casper the Friendly Ghost',
        "Chip 'n Dale: Rescue Rangers",
        'Clifford the Big Red Dog',
        'Danny Phantom',
        'DuckTales (2017)',
        'G.I. Joe: A Real American Hero',
        'Inspector Gadget (2015)',
        'Masha and the Bear',
        'Max & Ruby',
        'Mickey and the Roadster Racers',
        'PAW Patrol',
        'Peppa Pig',
        'PJ Masks',
        'Rainbow Ruby',
        'Ready Jet Go!',
        'Sonic X',
        'Sofia the First',
        'The Adventures of Jimmy Neutron: Boy Genius',
        'The Berenstain Bears',
        'The New Adventures of Winnie the Pooh',
        'The Octonauts',
        'The Scooby-Doo Show',
        'The Tick',
        'ThunderCats',
        'Timmy Time',
        'Totally Spies!',
        'Transformers: Animated',
        'Transformers: Prime',
        'Trollz'
    ],
    "cities": [
        'Mumbai',
        'Delhi',
        'Bangalore',
        'Kolkata',
        'Chennai',
        'Hyderabad',
        'Ahmedabad',
        'Pune',
        'Surat',
        'Jaipur',
        'Lucknow',
        'Kanpur',
        'Nagpur',
        'Patna',
        'Indore',
        'Thane',
        'Bhopal',
        'Visakhapatnam',
        'Vadodara',
        'Firozabad',
        'Ludhiana',
        'Rajkot',
        'Agra',
        'Siliguri',
        'Nashik',
        'Faridabad',
        'Patiala',
        'Meerut',
        'Kalyan-Dombivli',
        'Vasai-Virar',
        'Varanasi',
        'Srinagar',
        'Dhanbad',
        'Jodhpur',
        'Amritsar',
        'Raipur',
        'Allahabad',
        'Coimbatore',
        'Jabalpur',
        'Gwalior',
        'Vijayawada',
        'Madurai',
        'Guwahati',
        'Chandigarh',
        'Hubli-Dharwad',
        'Amroha',
        'Moradabad',
        'Gurgaon',
        'Aligarh',
        'Solapur',
        'Ranchi',
        'Jalandhar',
        'Tiruchirappalli',
        'Bhubaneswar',
        'Salem',
        'Warangal',
        'Mira-Bhayandar',
        'Jalgaon',
        'Guntur',
        'Thiruvananthapuram',
        'Bhiwandi',
        'Saharanpur',
        'Gorakhpur',
        'Bikaner',
        'Amravati',
        'Noida',
        'Jamshedpur',
        'Bhilai',
        'Cuttack',
        'Firozabad',
        'Kochi',
        'Nellore',
        'Bhavnagar',
        'Dehradun',
        'Durgapur',
        'Asansol',
        'Rourkela',
        'Nanded',
        'Kolhapur',
        'Ajmer',
        'Faridabad',
        'Delhi',
        'Akola',
        'Gulbarga',
        'Jamnagar',
        'Ujjain',
        'Loni',
        'Siliguri',
        'Jhansi',
        'Ulhasnagar',
        'Nellore',
        'Jammu',
        'Sangli-Miraj & Kupwad',
        'Belgaum',
        'Mangalore',
        'Ambattur',
        'Tirunelveli',
        'Malegaon',
        'Gaya',
        'Jalgaon',
        'Udaipur'
    ],
    "cars": [
        'Toyota',
        'Honda',
        'Ford',
        'BMW',
        'Mercedes-Benz',
        'Volkswagen',
        'Audi',
        'Hyundai',
        'Chevrolet',
        'Nissan',
        'Tesla',
        'Ferrari',
        'Porsche',
        'Lamborghini',
        'Subaru',
        'Mitsubishi',
        'Kia',
        'Mazda',
        'Volvo',
        'Jaguar',
        'Land Rover',
        'Jeep',
        'Chrysler',
        'Dodge',
        'Buick',
        'Cadillac',
        'Infiniti',
        'Lexus',
        'Acura',
        'Lincoln',
        'Alfa Romeo',
        'Bentley',
        'Maserati',
        'Mini',
        'Ram',
        'GMC',
        'Fiat',
        'Bugatti',
        'McLaren',
        'Pagani',
        'Rolls-Royce',
        'Suzuki',
        'Maybach',
        'Pontiac',
        'Saturn',
        'Saab',
        'Hummer',
        'Oldsmobile'
    ],
    "landmarks": [
        'Eiffel Tower',
        'Great Wall of China',
        'Statue of Liberty',
        'Taj Mahal',
        'Machu Picchu',
        'Pyramids of Giza',
        'Colosseum',
        'Stonehenge',
        'Burj Khalifa',
        'Petra',
        'Chichen Itza',
        'Angkor Wat',
        'Christ the Redeemer',
        'Sphinx',
        'Acropolis of Athens',
        'Alhambra',
        'Hagia Sophia',
        'Mount Everest',
        'Niagara Falls',
        'Grand Canyon',
        'Sydney Opera House',
        'Sagrada Familia',
        'Forbidden City',
        'Saint Basil’s Cathedral',
        'Potala Palace',
        'Big Ben',
        'Mesa Verde',
        'Terracotta Army',
        'Meteora',
        'Golden Gate Bridge',
        'Louvre Museum',
        'Red Square',
        'Versailles Palace',
        'Mona Lisa',
        'Tower Bridge',
        'The Shard',
        'Buckingham Palace',
        'Brooklyn Bridge',
        'Saint Peter’s Basilica',
        'Mausoleum at Halicarnassus',
        'CN Tower',
        'Neuschwanstein Castle',
        'Mont Saint-Michel',
        'Mount Rushmore',
        'Cappadocia',
        'Mojave Desert',
        'Kremlin',
        'Tower of London'
    ],
    "emotions": [
        "Joy",
        "Sadness",
        "Anger",
        "Fear",
        "Surprise",
        "Disgust",
        "Love",
        "Happiness",
        "Excitement",
        "Grief",
        "Melancholy",
        "Loneliness",
        "Anxiety",
        "Contentment",
        "Envy",
        "Frustration",
        "Pride",
        "Confusion",
        "Shame",
        "Regret",
        "Gratitude",
        "Hope",
        "Disappointment",
        "Amusement",
        "Awe",
        "Contempt",
        "Elation",
        "Despair",
        "Satisfaction",
        "Relief",
        "Guilt",
        "Remorse",
        "Nostalgia",
        "Boredom",
        "Tenderness",
        "Sympathy",
        "Empathy",
        "Compassion",
        "Euphoria",
        "Bitterness",
        "Hatred",
        "Jealousy",
        "Anticipation",
        "Shyness",
        "Panic",
        "Overwhelmed",
        "Serenity",
        "Hysteria",
        "Insecurity",
        "Eagerness"
    ],
    "objects": [
        "Chair",
        "Table",
        "Pen",
        "Car",
        "Book",
        "Laptop",
        "Phone",
        "Watch",
        "Bicycle",
        "Television",
        "Glasses",
        "Keys",
        "Door",
        "Window",
        "Shoes",
        "Headphones",
        "Spoon",
        "Fork",
        "Knife",
        "Plate",
        "Cup",
        "Water bottle",
        "Mirror",
        "Wallet",
        "Hat",
        "Scissors",
        "Remote control",
        "Camera",
        "Microphone",
        "Bag",
        "Chair",
        "Table",
        "Pen",
        "Car",
        "Book",
        "Laptop",
        "Phone",
        "Watch",
        "Bicycle",
        "Television",
        "Glasses",
        "Keys",
        "Door",
        "Window",
        "Shoes",
        "Headphones",
        "Spoon",
        "Fork",
        "Knife",
        "Plate",
        "Cup",
        "Water bottle",
        "Mirror",
        "Wallet",
        "Hat",
        "Scissors",
        "Remote control",
        "Camera",
        "Microphone",
        "Bag",
        "Chair",
        "Table",
        "Pen",
        "Car",
        "Book",
        "Laptop",
        "Phone",
        "Watch",
        "Bicycle",
        "Television",
        "Glasses",
        "Keys",
        "Door",
        "Window",
        "Shoes",
        "Headphones",
        "Spoon",
        "Fork",
        "Knife",
        "Plate",
        "Cup",
        "Water bottle",
        "Mirror",
        "Wallet",
        "Hat",
        "Scissors",
        "Remote control",
        "Camera",
        "Microphone",
        "Bag",
        "Chair",
        "Table",
        "Pen",
        "Car",
        "Book",
        "Laptop",
        "Phone",
        "Watch",
        "Bicycle",
        "Television",
        "Glasses",
        "Keys",
        "Door",
        "Window",
        "Shoes",
        "Headphones",
        "Spoon",
        "Fork",
        "Knife",
        "Plate",
        "Cup",
        "Water bottle",
        "Mirror",
        "Wallet",
        "Hat",
        "Scissors",
        "Remote control",
        "Camera",
        "Microphone",
        "Bag"
    ],
    "drinks": [
        "Water",
        "Coffee",
        "Tea",
        "Orange Juice",
        "Apple Juice",
        "Lemonade",
        "Mango Lassi",
        "Cola",
        "Lemon Soda",
        "Mojito",
        "Pina Colada",
        "Margarita",
        "Mai Tai",
        "Mimosa",
        "Bloody Mary",
        "Gin and Tonic",
        "Old Fashioned",
        "Martini",
        "Moscow Mule",
        "Whiskey Sour",
        "Negroni",
        "White Russian",
        "Cosmopolitan",
        "Paloma",
        "Screwdriver",
        "Irish Coffee",
        "Hot Chocolate",
        "Milkshake",
        "Smoothie",
        "Iced Tea",
        "Green Tea",
        "Black Tea",
        "Chai Latte",
        "Espresso",
        "Cappuccino",
        "Latte",
        "Americano",
        "Flat White",
        "Matcha Latte",
        "Turmeric Latte",
        "Chamomile Tea",
        "Peppermint Tea",
        "Chai Tea",
        "Bubble Tea",
        "Fruit Punch",
        "Limeade",
        "Peach Iced Tea",
        "Raspberry Iced Tea",
        "Arnold Palmer",
        "Sangria",
        "Piña Colada",
        "Strawberry Daiquiri",
        "Blue Lagoon",
        "Sex on the Beach",
        "White Russian",
        "Long Island Iced Tea",
        "Singapore Sling",
        "Mai Tai",
        "Margarita",
        "Mojito",
        "Cosmopolitan",
        "Bloody Mary",
        "Gin Fizz",
        "Tom Collins",
        "Dark 'n' Stormy",
        "Rum Punch",
        "Blue Hawaii",
        "Tequila Sunrise",
        "Mint Julep",
        "White Russian",
        "Martini",
        "Manhattan",
        "Whiskey Sour",
        "Hot Toddy",
        "French 75",
        "Negroni",
        "Bellini",
        "Kir Royale",
        "Paloma",
        "Greyhound",
        "Screwdriver",
        "Bay Breeze",
        "Sea Breeze",
        "Cuba Libre",
        "Black Russian",
        "Pink Lady",
        "Alabama Slammer",
        "Irish Coffee",
        "Mai Tai",
        "Pisco Sour",
        "Zombie",
        "Mudslide",
        "Pink Gin",
        "Long Island Iced Tea",
        "Sazerac",
        "Gimlet",
        "Corpse Reviver",
        "Hot Buttered Rum",
        "Moscow Mule",
        "Tequila Sunrise",
        "Jack and Coke",
        "Whiskey Ginger",
        "Amaretto Sour",
        "Piña Colada",
        "Tom Collins",
        "Strawberry Margarita",
        "Cranberry Vodka",
        "Vodka Tonic",
        "Mai Tai",
        "Mint Julep",
        "Blue Lagoon"
    ],
    "brands": [
        "Nike",
        "Apple",
        "Amazon",
        "Google",
        "Microsoft",
        "Samsung",
        "Adidas",
        "Coca-Cola",
        "Toyota",
        "BMW",
        "Mercedes-Benz",
        "Ford",
        "Disney",
        "Sony",
        "McDonald's",
        "Intel",
        "Louis Vuitton",
        "Honda",
        "Pepsi",
        "Nestle",
        "Lego",
        "Facebook",
        "Visa",
        "Mastercard",
        "IBM",
        "Burger King",
        "Audi",
        "Canon",
        "HP",
        "Dell",
        "Gucci",
        "H&M",
        "Zara",
        "Chanel",
        "Puma",
        "Volkswagen",
        "Netflix",
        "Adobe",
        "PayPal",
        "American Express",
        "L'Oréal",
        "IKEA",
        "Lamborghini",
        "Rolex",
        "Uber",
        "Airbnb",
        "Starbucks",
        "Uber Eats",
        "Xiaomi",
        "Tesla",
        "Spotify",
        "Nissan",
        "Nokia",
        "Colgate",
        "Bentley",
        "Heineken",
        "Cisco",
        "Oracle",
        "Panasonic",
        "Mitsubishi",
        "Subway",
        "Maserati",
        "KFC",
        "Hilton",
        "Hermès",
        "FedEx",
        "Gillette",
        "Tiffany & Co.",
        "WhatsApp",
        "Instagram",
        "Pinterest",
        "TikTok",
        "Snapchat",
        "Twitter",
        "LinkedIn",
        "YouTube",
        "Reddit",
        "WhatsApp",
        "Twitch",
        "Zoom",
        "Dropbox",
        "Ebay",
        "Walmart",
        "Target",
        "Costco",
        "Porsche",
        "Lexus",
        "Ferrari",
        "Burberry",
        "Dior",
        "Estée Lauder",
        "Maybelline",
        "Revlon",
        "GAP",
        "Chrysler",
        "Jaguar",
        "Mazda",
        "Lufthansa",
        "Qatar Airways",
        "Air France",
        "British Airways",
        "Lego",
        "Nintendo",
        "Fendi",
        "Hugo Boss",
        "Versace",
        "Tommy Hilfiger",
        "Prada",
        "GAP",
        "Chrysler",
        "Jaguar",
        "Mazda",
        "Lufthansa",
        "Qatar Airways",
        "Air France",
        "British Airways",
        "Lego",
        "Nintendo",
        "Calvin Klein",
        "Ralph Lauren",
        "Dolce & Gabbana",
        "Hollister",
        "Abercrombie & Fitch",
        "American Eagle",
        "Levi's",
        "Wrangler",
        "Gucci",
        "Victoria's Secret",
        "Forever 21",
        "H&M",
        "Zara",
        "Chanel",
        "Puma",
        "Volkswagen",
        "Netflix",
        "Adobe",
        "PayPal",
        "American Express",
        "L'Oréal",
        "IKEA",
        "Lamborghini",
        "Rolex",
        "Uber",
        "Airbnb",
        "Starbucks",
        "Uber Eats",
        "Xiaomi",
        "Tesla",
        "Spotify",
        "Nissan",
        "Nokia",
        "Colgate",
        "Bentley",
        "Heineken",
        "Cisco",
        "Oracle",
        "Panasonic",
        "Mitsubishi",
        "Subway",
        "Maserati",
        "KFC",
        "Hilton",
        "Hermès",
        "FedEx",
        "Gillette",
        "Tiffany & Co.",
        "WhatsApp",
        "Instagram",
        "Pinterest",
        "TikTok",
        "Snapchat",
        "Twitter",
        "LinkedIn",
        "YouTube",
        "Reddit",
        "WhatsApp",
        "Twitch",
        "Zoom",
        "Dropbox",
        "Ebay",
        "Walmart",
        "Target",
        "Costco",
        "Porsche",
        "Lexus",
        "Ferrari",
        "Burberry",
        "Dior",
        "Estée Lauder",
        "Maybelline",
        "Revlon",
        "Bose",
        "Bang & Olufsen",
        "Sharp",
        "Philips",
        "LG",
        "GoPro",
        "Canon",
        "Nikon",
        "PlayStation",
        "Xbox",
        "Nintendo",
        "Sega",
        "ASUS",
        "Alienware",
        "MSI",
        "Corsair",
        "Razer",
        "Logitech",
        "SteelSeries",
        "Sennheiser",
        "Bose",
        "JBL",
        "Sonos",
        "Bose",
        "Harman Kardon",
        "Yamaha",
    ]
}